name: angular_ui_demo
version: 0.3.0
authors:
- Sergey Akopkokhyants <akserg@gmail.com>
- Gunter Zochbauer <gzoechi@gmail.com>
description: Demo page for angular.dart.ui.
homepage: http://akserg.github.io/angular.dart.ui.demo
environment:
  sdk: '>=1.6.0 <2.0.0'
dependencies:
  browser: '>=0.10.0+2 <0.11.0'
  angular: '>=1.1.0 <2.0.0'
  angular_ui: '>=0.6.6 <0.7.0'
  logging_handlers: '>=0.8.0 <0.9.0'
  markdown: '>=0.7.1+2 <0.8.0'
transformers:
- angular
- $dart2js:
    commandLineOptions: [--enable-experimental-mirrors]
