library di.generated.type_factories;
import "package:angular_ui_demo/app/app.dart" as import_5;
import "package:angular/core/module.dart" as import_30;
import "package:angular/core_dom/module.dart" as import_31;
import "dart:html" as import_1;
import "package:angular/filter/module.dart" as import_33;
import "package:di/di.dart" as import_28;
import "package:angular_ui_demo/accordion/demo.dart" as import_8;
import "package:angular_ui_demo/alert/demo.dart" as import_9;
import "package:angular_ui_demo/collapse/demo.dart" as import_10;
import "package:angular_ui_demo/dropdown_toggle/demo.dart" as import_11;
import "package:angular_ui_demo/rating/demo.dart" as import_12;
import "package:angular/core/parser/parser.dart" as import_36;
import "package:perf_api/perf_api.dart" as import_50;
import "package:angular/directive/module.dart" as import_32;
import "package:angular/routing/module.dart" as import_35;
import "package:route_hierarchical/client.dart" as import_52;
import "package:angular/core/parser/lexer.dart" as import_37;
import "package:angular_ui/alert.dart" as import_41;
import "package:angular_ui/accordion/accordion.dart" as import_42;
import "package:angular_ui/buttons.dart" as import_43;
import "package:angular_ui/carousel.dart" as import_44;
import "package:angular_ui/collapse.dart" as import_45;
import "package:angular_ui/transition.dart" as import_59;
import "package:angular_ui/dropdown_toggle.dart" as import_46;
import "package:angular_ui/rating/rating.dart" as import_47;
import "package:angular_ui/timeout.dart" as import_48;
var typeFactories = new Map();
main() {
typeFactories[import_5.HeadController] = (f) => new import_5.HeadController(f(import_5.UiElementList));
typeFactories[import_5.MainController] = (f) => new import_5.MainController(f(import_30.Scope), f(import_31.Http), f(import_1.HtmlDocument), f(import_33.OrderByFilter), f(import_5.UiElementList), f(import_5.Package));
typeFactories[import_5.BaBindHtmlDirective] = (f) => new import_5.BaBindHtmlDirective(f(import_1.Element), f(import_30.Scope), f(import_28.Injector), f(import_31.Compiler));
typeFactories[import_8.AccordionDemoController] = (f) => new import_8.AccordionDemoController();
typeFactories[import_9.AlertDemoController] = (f) => new import_9.AlertDemoController();
typeFactories[import_10.CollapseDemoController] = (f) => new import_10.CollapseDemoController();
typeFactories[import_11.DropdownToggleDemoController] = (f) => new import_11.DropdownToggleDemoController();
typeFactories[import_12.RatingDemoController] = (f) => new import_12.RatingDemoController(f(import_30.Scope));
typeFactories[import_30.DirectiveMap] = (f) => new import_30.DirectiveMap(f(import_28.Injector), f(import_30.MetadataExtractor), f(import_30.FieldMetadataExtractor));
typeFactories[import_30.FieldMetadataExtractor] = (f) => new import_30.FieldMetadataExtractor();
typeFactories[import_30.ExceptionHandler] = (f) => new import_30.ExceptionHandler();
typeFactories[import_30.FilterMap] = (f) => new import_30.FilterMap(f(import_28.Injector), f(import_30.MetadataExtractor));
typeFactories[import_30.Interpolate] = (f) => new import_30.Interpolate(f(import_36.Parser));
typeFactories[import_30.MetadataExtractor] = (f) => new import_30.MetadataExtractor();
typeFactories[import_30.ScopeDigestTTL] = (f) => new import_30.ScopeDigestTTL();
typeFactories[import_30.Scope] = (f) => new import_30.Scope(f(import_30.ExceptionHandler), f(import_36.Parser), f(import_30.ScopeDigestTTL), f(import_30.NgZone), f(import_50.Profiler));
typeFactories[import_31.BlockCache] = (f) => new import_31.BlockCache(f(import_31.Http), f(import_31.TemplateCache), f(import_31.Compiler), f(import_1.NodeTreeSanitizer));
typeFactories[import_31.BrowserCookies] = (f) => new import_31.BrowserCookies(f(import_30.ExceptionHandler));
typeFactories[import_31.Compiler] = (f) => new import_31.Compiler(f(import_30.DirectiveMap), f(import_50.Profiler), f(import_36.Parser), f(Expando));
typeFactories[import_31.UrlRewriter] = (f) => new import_31.UrlRewriter();
typeFactories[import_31.HttpBackend] = (f) => new import_31.HttpBackend();
typeFactories[import_31.LocationWrapper] = (f) => new import_31.LocationWrapper();
typeFactories[import_31.HttpInterceptors] = (f) => new import_31.HttpInterceptors();
typeFactories[import_31.HttpDefaultHeaders] = (f) => new import_31.HttpDefaultHeaders();
typeFactories[import_31.HttpDefaults] = (f) => new import_31.HttpDefaults(f(import_31.HttpDefaultHeaders));
typeFactories[import_31.Http] = (f) => new import_31.Http(f(import_31.BrowserCookies), f(import_31.LocationWrapper), f(import_31.UrlRewriter), f(import_31.HttpBackend), f(import_31.HttpDefaults), f(import_31.HttpInterceptors));
typeFactories[import_31.NgTextMustacheDirective] = (f) => new import_31.NgTextMustacheDirective(f(import_1.Node), f(String), f(import_30.Interpolate), f(import_30.Scope), f(import_31.TextChangeListener));
typeFactories[import_31.NgAttrMustacheDirective] = (f) => new import_31.NgAttrMustacheDirective(f(import_31.NodeAttrs), f(String), f(import_30.Interpolate), f(import_30.Scope));
typeFactories[import_31.NullTreeSanitizer] = (f) => new import_31.NullTreeSanitizer();
typeFactories[import_32.NgADirective] = (f) => new import_32.NgADirective(f(import_1.Element));
typeFactories[import_32.NgBindDirective] = (f) => new import_32.NgBindDirective(f(import_1.Element));
typeFactories[import_32.NgBindHtmlDirective] = (f) => new import_32.NgBindHtmlDirective(f(import_1.Element));
typeFactories[import_32.NgBindTemplateDirective] = (f) => new import_32.NgBindTemplateDirective(f(import_1.Element));
typeFactories[import_32.NgClassDirective] = (f) => new import_32.NgClassDirective(f(import_1.Element), f(import_30.Scope), f(import_31.NodeAttrs));
typeFactories[import_32.NgClassOddDirective] = (f) => new import_32.NgClassOddDirective(f(import_1.Element), f(import_30.Scope), f(import_31.NodeAttrs));
typeFactories[import_32.NgClassEvenDirective] = (f) => new import_32.NgClassEvenDirective(f(import_1.Element), f(import_30.Scope), f(import_31.NodeAttrs));
typeFactories[import_32.NgEventDirective] = (f) => new import_32.NgEventDirective(f(import_1.Element), f(import_30.Scope));
typeFactories[import_32.NgEventDirective] = (f) => new import_32.NgEventDirective(f(import_1.Element), f(import_30.Scope));
typeFactories[import_32.NgEventDirective] = (f) => new import_32.NgEventDirective(f(import_1.Element), f(import_30.Scope));
typeFactories[import_32.NgEventDirective] = (f) => new import_32.NgEventDirective(f(import_1.Element), f(import_30.Scope));
typeFactories[import_32.NgEventDirective] = (f) => new import_32.NgEventDirective(f(import_1.Element), f(import_30.Scope));
typeFactories[import_32.NgEventDirective] = (f) => new import_32.NgEventDirective(f(import_1.Element), f(import_30.Scope));
typeFactories[import_32.NgEventDirective] = (f) => new import_32.NgEventDirective(f(import_1.Element), f(import_30.Scope));
typeFactories[import_32.NgEventDirective] = (f) => new import_32.NgEventDirective(f(import_1.Element), f(import_30.Scope));
typeFactories[import_32.NgEventDirective] = (f) => new import_32.NgEventDirective(f(import_1.Element), f(import_30.Scope));
typeFactories[import_32.NgEventDirective] = (f) => new import_32.NgEventDirective(f(import_1.Element), f(import_30.Scope));
typeFactories[import_32.NgEventDirective] = (f) => new import_32.NgEventDirective(f(import_1.Element), f(import_30.Scope));
typeFactories[import_32.NgEventDirective] = (f) => new import_32.NgEventDirective(f(import_1.Element), f(import_30.Scope));
typeFactories[import_32.NgEventDirective] = (f) => new import_32.NgEventDirective(f(import_1.Element), f(import_30.Scope));
typeFactories[import_32.NgEventDirective] = (f) => new import_32.NgEventDirective(f(import_1.Element), f(import_30.Scope));
typeFactories[import_32.NgEventDirective] = (f) => new import_32.NgEventDirective(f(import_1.Element), f(import_30.Scope));
typeFactories[import_32.NgEventDirective] = (f) => new import_32.NgEventDirective(f(import_1.Element), f(import_30.Scope));
typeFactories[import_32.NgEventDirective] = (f) => new import_32.NgEventDirective(f(import_1.Element), f(import_30.Scope));
typeFactories[import_32.NgEventDirective] = (f) => new import_32.NgEventDirective(f(import_1.Element), f(import_30.Scope));
typeFactories[import_32.NgEventDirective] = (f) => new import_32.NgEventDirective(f(import_1.Element), f(import_30.Scope));
typeFactories[import_32.NgEventDirective] = (f) => new import_32.NgEventDirective(f(import_1.Element), f(import_30.Scope));
typeFactories[import_32.NgEventDirective] = (f) => new import_32.NgEventDirective(f(import_1.Element), f(import_30.Scope));
typeFactories[import_32.NgEventDirective] = (f) => new import_32.NgEventDirective(f(import_1.Element), f(import_30.Scope));
typeFactories[import_32.NgEventDirective] = (f) => new import_32.NgEventDirective(f(import_1.Element), f(import_30.Scope));
typeFactories[import_32.NgEventDirective] = (f) => new import_32.NgEventDirective(f(import_1.Element), f(import_30.Scope));
typeFactories[import_32.NgEventDirective] = (f) => new import_32.NgEventDirective(f(import_1.Element), f(import_30.Scope));
typeFactories[import_32.NgEventDirective] = (f) => new import_32.NgEventDirective(f(import_1.Element), f(import_30.Scope));
typeFactories[import_32.NgEventDirective] = (f) => new import_32.NgEventDirective(f(import_1.Element), f(import_30.Scope));
typeFactories[import_32.NgEventDirective] = (f) => new import_32.NgEventDirective(f(import_1.Element), f(import_30.Scope));
typeFactories[import_32.NgEventDirective] = (f) => new import_32.NgEventDirective(f(import_1.Element), f(import_30.Scope));
typeFactories[import_32.NgEventDirective] = (f) => new import_32.NgEventDirective(f(import_1.Element), f(import_30.Scope));
typeFactories[import_32.NgEventDirective] = (f) => new import_32.NgEventDirective(f(import_1.Element), f(import_30.Scope));
typeFactories[import_32.NgEventDirective] = (f) => new import_32.NgEventDirective(f(import_1.Element), f(import_30.Scope));
typeFactories[import_32.NgEventDirective] = (f) => new import_32.NgEventDirective(f(import_1.Element), f(import_30.Scope));
typeFactories[import_32.NgEventDirective] = (f) => new import_32.NgEventDirective(f(import_1.Element), f(import_30.Scope));
typeFactories[import_32.NgEventDirective] = (f) => new import_32.NgEventDirective(f(import_1.Element), f(import_30.Scope));
typeFactories[import_32.NgEventDirective] = (f) => new import_32.NgEventDirective(f(import_1.Element), f(import_30.Scope));
typeFactories[import_32.NgEventDirective] = (f) => new import_32.NgEventDirective(f(import_1.Element), f(import_30.Scope));
typeFactories[import_32.NgEventDirective] = (f) => new import_32.NgEventDirective(f(import_1.Element), f(import_30.Scope));
typeFactories[import_32.NgEventDirective] = (f) => new import_32.NgEventDirective(f(import_1.Element), f(import_30.Scope));
typeFactories[import_32.NgEventDirective] = (f) => new import_32.NgEventDirective(f(import_1.Element), f(import_30.Scope));
typeFactories[import_32.NgEventDirective] = (f) => new import_32.NgEventDirective(f(import_1.Element), f(import_30.Scope));
typeFactories[import_32.NgEventDirective] = (f) => new import_32.NgEventDirective(f(import_1.Element), f(import_30.Scope));
typeFactories[import_32.NgEventDirective] = (f) => new import_32.NgEventDirective(f(import_1.Element), f(import_30.Scope));
typeFactories[import_32.NgEventDirective] = (f) => new import_32.NgEventDirective(f(import_1.Element), f(import_30.Scope));
typeFactories[import_32.NgEventDirective] = (f) => new import_32.NgEventDirective(f(import_1.Element), f(import_30.Scope));
typeFactories[import_32.NgEventDirective] = (f) => new import_32.NgEventDirective(f(import_1.Element), f(import_30.Scope));
typeFactories[import_32.NgEventDirective] = (f) => new import_32.NgEventDirective(f(import_1.Element), f(import_30.Scope));
typeFactories[import_32.NgEventDirective] = (f) => new import_32.NgEventDirective(f(import_1.Element), f(import_30.Scope));
typeFactories[import_32.NgEventDirective] = (f) => new import_32.NgEventDirective(f(import_1.Element), f(import_30.Scope));
typeFactories[import_32.NgEventDirective] = (f) => new import_32.NgEventDirective(f(import_1.Element), f(import_30.Scope));
typeFactories[import_32.NgCloakDirective] = (f) => new import_32.NgCloakDirective(f(import_1.Element));
typeFactories[import_32.NgCloakDirective] = (f) => new import_32.NgCloakDirective(f(import_1.Element));
typeFactories[import_32.NgIfDirective] = (f) => new import_32.NgIfDirective(f(import_31.BoundBlockFactory), f(import_31.BlockHole), f(import_30.Scope));
typeFactories[import_32.NgUnlessDirective] = (f) => new import_32.NgUnlessDirective(f(import_31.BoundBlockFactory), f(import_31.BlockHole), f(import_30.Scope));
typeFactories[import_32.NgIncludeDirective] = (f) => new import_32.NgIncludeDirective(f(import_1.Element), f(import_30.Scope), f(import_31.BlockCache), f(import_28.Injector));
typeFactories[import_32.NgModel] = (f) => new import_32.NgModel(f(import_30.Scope), f(import_31.NodeAttrs));
typeFactories[import_32.InputCheckboxDirective] = (f) => new import_32.InputCheckboxDirective(f(import_1.Element), f(import_32.NgModel), f(import_30.Scope));
typeFactories[import_32.InputTextDirective] = (f) => new import_32.InputTextDirective(f(import_1.Element), f(import_32.NgModel), f(import_30.Scope));
typeFactories[import_32.InputPasswordDirective] = (f) => new import_32.InputPasswordDirective(f(import_1.Element), f(import_32.NgModel), f(import_30.Scope));
typeFactories[import_32.TextAreaDirective] = (f) => new import_32.TextAreaDirective(f(import_1.Element), f(import_32.NgModel), f(import_30.Scope));
typeFactories[import_32.InputNumberDirective] = (f) => new import_32.InputNumberDirective(f(import_1.Element), f(import_32.NgModel), f(import_30.Scope));
typeFactories[import_32.InputEmailDirective] = (f) => new import_32.InputEmailDirective(f(import_1.Element), f(import_32.NgModel), f(import_30.Scope));
typeFactories[import_32.InputUrlDirective] = (f) => new import_32.InputUrlDirective(f(import_1.Element), f(import_32.NgModel), f(import_30.Scope));
typeFactories[import_32.InputRadioDirective] = (f) => new import_32.InputRadioDirective(f(import_1.Element), f(import_32.NgModel), f(import_30.Scope), f(import_31.NodeAttrs));
typeFactories[import_32.NgPluralizeDirective] = (f) => new import_32.NgPluralizeDirective(f(import_30.Scope), f(import_1.Element), f(import_30.Interpolate), f(import_31.NodeAttrs));
typeFactories[import_32.NgPluralizeDirective] = (f) => new import_32.NgPluralizeDirective(f(import_30.Scope), f(import_1.Element), f(import_30.Interpolate), f(import_31.NodeAttrs));
typeFactories[import_32.NgRepeatDirective] = (f) => new import_32.NgRepeatDirective(f(import_31.BlockHole), f(import_31.BoundBlockFactory), f(import_30.Scope));
typeFactories[import_32.NgShalowRepeatDirective] = (f) => new import_32.NgShalowRepeatDirective(f(import_31.BlockHole), f(import_31.BoundBlockFactory), f(import_30.Scope));
typeFactories[import_32.NgTemplateDirective] = (f) => new import_32.NgTemplateDirective(f(import_1.Element), f(import_31.TemplateCache));
typeFactories[import_32.NgTemplateDirective] = (f) => new import_32.NgTemplateDirective(f(import_1.Element), f(import_31.TemplateCache));
typeFactories[import_32.NgHideDirective] = (f) => new import_32.NgHideDirective(f(import_1.Element));
typeFactories[import_32.NgShowDirective] = (f) => new import_32.NgShowDirective(f(import_1.Element));
typeFactories[import_32.NgBooleanAttributeDirective] = (f) => new import_32.NgBooleanAttributeDirective(f(import_31.NodeAttrs));
typeFactories[import_32.NgBooleanAttributeDirective] = (f) => new import_32.NgBooleanAttributeDirective(f(import_31.NodeAttrs));
typeFactories[import_32.NgBooleanAttributeDirective] = (f) => new import_32.NgBooleanAttributeDirective(f(import_31.NodeAttrs));
typeFactories[import_32.NgBooleanAttributeDirective] = (f) => new import_32.NgBooleanAttributeDirective(f(import_31.NodeAttrs));
typeFactories[import_32.NgBooleanAttributeDirective] = (f) => new import_32.NgBooleanAttributeDirective(f(import_31.NodeAttrs));
typeFactories[import_32.NgBooleanAttributeDirective] = (f) => new import_32.NgBooleanAttributeDirective(f(import_31.NodeAttrs));
typeFactories[import_32.NgBooleanAttributeDirective] = (f) => new import_32.NgBooleanAttributeDirective(f(import_31.NodeAttrs));
typeFactories[import_32.NgSourceDirective] = (f) => new import_32.NgSourceDirective(f(import_31.NodeAttrs));
typeFactories[import_32.NgSourceDirective] = (f) => new import_32.NgSourceDirective(f(import_31.NodeAttrs));
typeFactories[import_32.NgSourceDirective] = (f) => new import_32.NgSourceDirective(f(import_31.NodeAttrs));
typeFactories[import_32.NgStyleDirective] = (f) => new import_32.NgStyleDirective(f(import_1.Element), f(import_30.Scope));
typeFactories[import_32.NgSwitchDirective] = (f) => new import_32.NgSwitchDirective(f(import_30.Scope));
typeFactories[import_32.NgSwitchWhenDirective] = (f) => new import_32.NgSwitchWhenDirective(f(import_32.NgSwitchDirective), f(import_31.BlockHole), f(import_31.BoundBlockFactory), f(import_30.Scope));
typeFactories[import_32.NgSwitchDefaultDirective] = (f) => new import_32.NgSwitchDefaultDirective(f(import_32.NgSwitchDirective), f(import_31.BlockHole), f(import_31.BoundBlockFactory), f(import_30.Scope));
typeFactories[import_32.NgNonBindableDirective] = (f) => new import_32.NgNonBindableDirective();
typeFactories[import_32.InputSelectDirective] = (f) => new import_32.InputSelectDirective(f(import_1.Element), f(import_31.NodeAttrs), f(import_32.NgModel), f(import_30.Scope));
typeFactories[import_32.OptionValueDirective] = (f) => new import_32.OptionValueDirective(f(import_31.NodeAttrs), f(import_32.InputSelectDirective));
typeFactories[import_32.NgForm] = (f) => new import_32.NgForm(f(import_30.Scope), f(import_1.Element));
typeFactories[import_33.CurrencyFilter] = (f) => new import_33.CurrencyFilter();
typeFactories[import_33.DateFilter] = (f) => new import_33.DateFilter();
typeFactories[import_33.FilterFilter] = (f) => new import_33.FilterFilter(f(import_36.Parser));
typeFactories[import_33.JsonFilter] = (f) => new import_33.JsonFilter();
typeFactories[import_33.LimitToFilter] = (f) => new import_33.LimitToFilter(f(import_28.Injector));
typeFactories[import_33.LowercaseFilter] = (f) => new import_33.LowercaseFilter();
typeFactories[import_33.NumberFilter] = (f) => new import_33.NumberFilter();
typeFactories[import_33.OrderByFilter] = (f) => new import_33.OrderByFilter(f(import_36.Parser));
typeFactories[import_33.UppercaseFilter] = (f) => new import_33.UppercaseFilter();
typeFactories[import_35.NgRoutingUsePushState] = (f) => new import_35.NgRoutingUsePushState();
typeFactories[import_35.NgRoutingHelper] = (f) => new import_35.NgRoutingHelper(f(import_35.RouteInitializer), f(import_52.Router));
typeFactories[import_35.NgViewDirective] = (f) => new import_35.NgViewDirective(f(import_1.Element), f(import_31.BlockCache), f(import_30.Scope), f(import_28.Injector), f(import_52.Router));
typeFactories[import_35.NgBindRouteDirective] = (f) => new import_35.NgBindRouteDirective(f(import_52.Router), f(import_28.Injector), f(import_35.NgRoutingHelper));
typeFactories[import_37.Lexer] = (f) => new import_37.Lexer();
typeFactories[import_41.Alert] = (f) => new import_41.Alert();
typeFactories[import_42.AccordionComponent] = (f) => new import_42.AccordionComponent(f(import_30.Scope), f(import_42.AccordionConfig));
typeFactories[import_42.AccordionGroupComponent] = (f) => new import_42.AccordionGroupComponent(f(import_30.Scope), f(import_42.AccordionComponent));
typeFactories[import_42.AccordionHeadingComponent] = (f) => new import_42.AccordionHeadingComponent(f(import_30.Scope), f(import_42.AccordionGroupComponent));
typeFactories[import_43.BtnRadio] = (f) => new import_43.BtnRadio(f(import_1.Element), f(import_32.NgModel), f(import_43.ButtonConfig), f(import_30.Scope));
typeFactories[import_43.BtnCheckbox] = (f) => new import_43.BtnCheckbox(f(import_1.Element), f(import_32.NgModel), f(import_43.ButtonConfig), f(import_30.Scope));
typeFactories[import_44.Carousel] = (f) => new import_44.Carousel();
typeFactories[import_44.Slide] = (f) => new import_44.Slide(f(import_30.Scope), f(import_1.Element), f(import_44.CarouselController));
typeFactories[import_45.Collapse] = (f) => new import_45.Collapse(f(import_1.Element), f(import_59.Transition), f(import_30.Scope));
typeFactories[import_46.DropdownToggle] = (f) => new import_46.DropdownToggle(f(import_1.Element), f(import_30.Scope));
typeFactories[import_47.RatingComponent] = (f) => new import_47.RatingComponent(f(import_30.Scope), f(import_47.RatingConfig));
typeFactories[import_48.Timeout] = (f) => new import_48.Timeout(f(import_30.Scope), f(import_30.ExceptionHandler));
typeFactories[import_59.Transition] = (f) => new import_59.Transition(f(import_48.Timeout));
}
